namePrefix: '{{ include "chart.fullname" . }}-'

namespace: '{{ .Release.Namespace | quote }}'

generatorOptions:
  disableNameSuffixHash: true

patches:
  - clusterRoleBinding.patch.yaml

bases:
  - ../../rbac